# Generated by Django 4.0.6 on 2022-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('Allgemeinarzt', 'Allgemeinarzt'), ('Radiologe', 'Radiologe'), ('Uruloge', 'Uruloge'), ('Psychater', 'Psychater'), ('Kinderarzt', 'Kinderarzt')], max_length=128)),
                ('title', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
