# Generated by Django 4.0.6 on 2022-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Prof. Dr.', 'Prof. Dr.')], max_length=64),
        ),
    ]
